### ISSUE TITLE
Support for Epolis (just solved actually).

### ISSUE THREAD

**Issue by whowechina** [aixxe/2dxcamhook#2]

**Comment by try2crack** [comment]
> _No description provided._

I did the work, perhaps you can add a new source file for "Epolis 003-2023101800" with these codes
```
#include <cstddef>
std::ptrdiff_t addr_hook_a = 0x77D0E0;
std::ptrdiff_t addr_hook_b = 0x7E6DA0;
std::ptrdiff_t addr_textures =0x76D1328;
std::ptrdiff_t addr_device_offset = 0x00000E0;
```

**Comment by whowechina** [comment]
Before my PR gets accepted, you can download this DLL file here.

[2dxcamhook.LDJ-003-2023101800.dll.zip](https://github.com/aixxe/2dxcamhook/files/13626786/2dxcamhook.LDJ-003-2023101800.dll.zip)
